## 2.1 数据操作

**导入torch，查看其版本**

In [3]:
import torch
torch.__version__

'1.8.1+cpu'

### 2.1.1 创建Tensor(张量)

- 用arange(可不是arrange)创建一个行向量x，默认是浮点数，即torch.FlaotTensor的简写
- 张量中的每个值都称为张量的元素（element）
- 单行张量即寻常意义上的向量

In [34]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

**通过张量的shape属性或调用size函数访问张量形状**

In [37]:
print(x.shape)
print(x.size())

torch.Size([12])
torch.Size([12])


**获悉张量中元素的总数，即其size**

In [38]:
print(x.numel())

12


- 重置张量的形状，而不改变其数值大小
- 无需手动指定每个维度，因为某个维度，如高度得知后，宽度可以隐式自动得出
- 自动推断的维度可以用 -1 指代

In [39]:
x.reshape(3,-1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

**设置一个形状为(2,3,4)，数值全为 0 的Long型张量y**

In [40]:
y = torch.zeros((2,3,4),dtype=torch.long)
print(y)
y.dtype

tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]])


torch.int64

**注意到这里的参数可以是list，也可以是tuple**

In [41]:
y = torch.zeros([2,3,4])
y

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

**设置一个形状为(2,3,4)，数值全为1 的Long型张量y**

In [42]:
y = torch.ones([2,3,4])
y

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

- 创建一个3x4的随机初始化的`Tensor`
- 其中的每个element都从均值为0、标准差为1的标准高斯（正态）分布中随机采样。

In [43]:
torch.randn(3,4)

tensor([[-0.7911, -0.0209, -0.7185,  0.5186],
        [-1.3125,  0.1920,  0.5428, -2.2188],
        [ 0.2590, -1.0297, -0.5008,  0.2734]])

- 提供包含数值的 Python 列表（或嵌套列表）来为所需张量中的每个元素赋予确定值。
- 最外层的列表对应于轴 0，内层的列表对应于轴 1,直接根据数据创建:

In [44]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [45]:
torch.tensor([4,3])

tensor([4, 3])

**还可以通过现有的`Tensor`来创建，此方法会默认重用输入`Tensor`的一些属性，例如数据类型，除非自定义数据类型**

In [46]:
x = x.new_ones(5, 3, dtype=torch.float64)      # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 指定新的数据类型,但其结构保持一致
print(x)   

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.9181, -0.0404,  0.2881],
        [-0.0075, -0.9145, -1.0886],
        [-0.2666,  0.1894, -0.2190],
        [ 2.0576, -0.0354,  0.0627],
        [-0.7663,  1.0993,  2.7565]])


## 2.1.2 运算

### 算术运算

#### 加减乘除幂次

In [56]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2], dtype = float)
x + y, x - y, x * y, x / y, x**y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.], dtype=torch.float64),
 tensor([-1.,  0.,  2.,  6.], dtype=torch.float64),
 tensor([ 2.,  4.,  8., 16.], dtype=torch.float64),
 tensor([0.5000, 1.0000, 2.0000, 4.0000], dtype=torch.float64),
 tensor([ 1.,  4., 16., 64.], dtype=torch.float64))

In [57]:
torch.exp(x) # 对x张量上的每一个数值进行e的幂次计算

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

#### 加法操作的额外表达

In [58]:
res = torch.empty(4)
torch.add(x, y, out = res)
res

tensor([ 3.,  4.,  6., 10.])

**直接在原数据上修改**

In [59]:
y.add_(x)
y

tensor([ 3.,  4.,  6., 10.], dtype=torch.float64)

### 索引
我们还可以使用类似NumPy的索引操作来访问`Tensor`的一部分，需要注意的是：**索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。** 

In [66]:
print(x, y)
y = x[:]
y += 1
y, x[:] # 源tensor也被改了

tensor([ 3.,  4.,  6., 10.]) tensor([ 3.,  4.,  6., 10.])


(tensor([ 4.,  5.,  7., 11.]), tensor([ 4.,  5.,  7., 11.]))

如果不想共享内存， 需要先用clone操作创建一个副本再操作

In [69]:
print(x, y)
y = x.clone()[:]
y += 1
y, x[:] 

tensor([ 4.,  5.,  7., 11.]) tensor([ 5.,  6.,  8., 12.])


(tensor([ 5.,  6.,  8., 12.]), tensor([ 4.,  5.,  7., 11.]))

### 线性代数运算

#### 连结

- 可以把多个张量连结在一起，把它们端对端地叠起来形成一个更大的张量
- 只需要提供张量列表，并给出沿哪个轴连结
- 沿行连接（轴-0，形状的第一个元素），按列连接（轴-1，形状的第二个元素）
- 下例中：
    - 第一个输出张量的轴-0长度 ( 6 ) 是两个输入张量轴-0长度的总和 ( 3+3 )；
    - 第二个输出张量的轴-1长度 ( 8 ) 是两个输入张量轴-1长度的总和 ( 4+4 )

In [60]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y, torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

#### 逻辑运算符表示

In [61]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

#### 求和

**对张量中的所有元素进行求和会产生一个只有一个元素的张量**

In [62]:
X.sum()

tensor(66.)

## 2.1.3 广播机制

- Broadcasting即广播，是NumPy里的一种机制，它通常发生在两个具有不同shape数组做加减运算时
- 广播是从内向外的扩展元素的，所以需要将两个元素从后往前对比
- 可以广播的常见情形
    1. 两个数组各维度大小从后往前比对均一致
    2. 两个数组存在一些维度大小不相等时，有一个数组的该不相等维度大小为1
 https://zhuanlan.zhihu.com/p/145719622

In [70]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [71]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 2.1.4 索引和切片

- 规则与Python语法一致
- 可以用 [-1] 选择最后一个元素，可以用 [1:3] 选择第二个和第三个元素

In [72]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

**可以通过指定索引来将元素写入矩阵**

In [73]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

- 如果我们想为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值
- 例如，[0:2, :] 访问第1行和第2行，其中 “:” 代表沿轴 1（列）的所有元素

In [74]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 2.1.5. 节省内存

- 运行一些操作可能会导致为新结果分配内存。例如，如果我们用 Y = X + Y，我们将取消引用 Y 指向的张量，而是指向新分配的内存处的张量。
- Python 的 id() 函数演示了这一点，它给我们提供了内存中引用对象的确切地址。

In [75]:
before = id(Y)
Y = Y + X
id(Y) == before

False

我们可以使用 X[:] = X + Y 或 X += Y 来减少操作的内存开销

In [78]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2165458103040
id(Z): 2165458103040


In [79]:
before = id(X)
X += Y
id(X) == before

True

## 2.1.6. 转换为其他 Python 对象

numpy()和from_numpy()这两个函数产生的Tensor和NumPy array实际是使用的相同的内存，改变其中一个时另一个也会改变

In [80]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

要将大小为1的张量转换为 Python 标量，我们可以调用 item 函数或 Python 的内置函数

In [81]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)